# Generated by Django 4.0.4 on 2022-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karbaruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('tell', models.CharField(max_length=200, verbose_name='موبایل')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name_plural': 'تنظیمات کاربران',
            },
        ),
    ]
